# Configuration for https://github.com/actions/stale

name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          clos-issue-message: 'This issue has been automatically closed because it has become stale.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-pr-message: 'This pull request has been automatically closed because it has become stale.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,dependencies,epic'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
